"""Generates the sourceable __icon_map function from the installed sketchybar-app-font.

The font embeds its app mapping as JSON in the `meta` table under the `APPM` tag
(see https://github.com/kvndrsslr/sketchybar-app-font#configure-sketchybar), so the
map is derived from the font itself and cannot drift from it. Codepoints shift
between releases, which is why this runs at startup instead of being committed.

Output is a bash 3.2 `case` function: sourcing it keeps lookups in-process, which
matters for the long-lived aerospace subscriber. The file is only rewritten when
the font's release changes.

Usage: gen_icon_map.py [font] [output]
"""

import json
import os
import struct
import sys

HOME = os.path.expanduser("~")
DEFAULT_FONT = os.path.join(HOME, "Library/Fonts/sketchybar-app-font.ttf")
# Keep in sync with ICON_MAP_CACHE in helpers/icon_map.sh.
DEFAULT_OUTPUT = os.path.join(
    os.environ.get("XDG_CACHE_HOME") or os.path.join(HOME, ".cache"),
    "sketchybar/icon_map.sh",
)


def read_appm(path):
    with open(path, "rb") as f:
        buf = f.read()
    tables = {}
    for i in range(struct.unpack(">H", buf[4:6])[0]):
        o = 12 + i * 16
        tables[buf[o : o + 4].decode("latin1")] = struct.unpack(">I", buf[o + 8 : o + 12])[0]
    if "meta" not in tables:
        sys.exit(f"{path} has no meta table; sketchybar-app-font 2.0.87+ is required")
    meta = tables["meta"]
    # The first (and only) data map record follows the 16-byte meta header.
    tag = buf[meta + 16 : meta + 20]
    offset, length = struct.unpack(">II", buf[meta + 20 : meta + 28])
    if tag != b"APPM":
        sys.exit(f"{path}: expected APPM data map, found {tag!r}")
    return json.loads(buf[meta + offset : meta + offset + length])


def quote(s):
    return '"' + "".join("\\" + c if c in '\\"$`' else c for c in s) + '"'


def render(appm):
    exact, prefix, default = [], [], None
    for ligature, codepoint, app_names in appm["icons"]:
        glyph = chr(codepoint)
        if ligature == ":default:":
            default = glyph
        for name in app_names or []:
            if name.endswith("*"):
                prefix.append((name[:-1], glyph))
            else:
                exact.append((name, glyph))

    # `case` takes the first match, so exact names go before any prefix pattern
    # that could swallow them, and longer prefixes before shorter ones.
    prefix.sort(key=lambda p: -len(p[0]))
    lines = [
        "# Generated by helpers/gen_icon_map.py from sketchybar-app-font. Do not edit.",
        f"ICON_MAP_RELEASE={quote(appm['release'])}",
        "__icon_map() {",
        '  case "$1" in',
    ]
    for name, glyph in exact:
        lines.append(f'  {quote(name)}) icon_result="{glyph}" ;;')
    for name, glyph in prefix:
        lines.append(f'  {quote(name)}*) icon_result="{glyph}" ;;')
    lines.append(f'  *) icon_result="{default or ":default:"}" ;;')
    lines += ["  esac", "}", ""]
    return "\n".join(lines)


def cached_release(path):
    try:
        with open(path, encoding="utf-8") as f:
            f.readline()
            return f.readline().strip()
    except OSError:
        return None


def main():
    font = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    output = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT
    appm = read_appm(font)
    if cached_release(output) == f"ICON_MAP_RELEASE={quote(appm['release'])}":
        return
    os.makedirs(os.path.dirname(output), exist_ok=True)
    # Written beside the target and renamed so a plugin sourcing it mid-write
    # never sees half a function.
    tmp = f"{output}.{os.getpid()}"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(render(appm))
    os.replace(tmp, output)


if __name__ == "__main__":
    main()
