#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

source "$ITEM_DIR/apple.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- Right Side Of Notch Items --
source "$ITEM_DIR/media.sh"

# -- Right side --

# Add the clock
# Kill any previous clock helper
killall clock 2>/dev/null
# Build the helper
(cd "$CONFIG_DIR/scripts/clock" && make)
"$CONFIG_DIR/scripts/clock/clock" &

source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/caffeinate.sh"

sketchybar --hotload true
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
